version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  assignees:
  - jmasonlee
  - reho.balazs
  - brianberzins
  allow:
  - dependency-type: direct
  - dependency-type: indirect
