name: Python CI
on:
  release:
    types: [created]    
  workflow_dispatch:

jobs:    
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m pip install --upgrade build
          python3 -m pip install --upgrade twine
          python3 -m build
          twine upload dist/*
